### ISSUE TITLE
TrNsLtE

### ISSUE THREAD

**Issue by SuperAdam47** [Cosmoverse/FloatingText#1]
Does this plugin have language translation feature?
If this feature is not available, can you add it?

**Comment by Muqsit** [comment]
What do you mean by translation?

**Comment by SuperAdam47** [comment]
Example: I will create a flying post and every player will read it in their language

**Comment by Muqsit** [comment]
Ah, the plugin doesn't have that feature but you can use the API to do stuff like that. https://github.com/Cosmoverse/FloatingText#api

**Comment by SuperAdam47** [comment]
im not developer how to do it this iS
