### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [Cosmoverse/FloatingText#5]
Error: "Call to a member function close() on null" (EXCEPTION) in "plugins/FloatingText_dev16.phar/src/cosmicpe/floatingtext/Loader" at line 36

**Comment by Muqsit** [comment]
Too vague, send backtrace.

**Comment by ghost** [comment]
`Error: Class 'poggit\libasynql\libasynql' not found 
File: plugins/FloatingText_dev-17.phar/src/cosmicpe/floatingtext/db/Database
Line: 19
Type: Error`

**Comment by ghost** [comment]
`Error: "Typed property cosmicpe\floatingtext\Loader::$database must not be accessed before initialization" (EXCEPTION) in "plugins/FloatingText_dev-17.phar/src/cosmicpe/floatingtext/Loader" at line 35`
