### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AIPTU** [Cosmoverse/FloatingText#6]
Error: "Class "poggit\libasynql\libasynql" not found" (EXCEPTION) in "plugins/FloatingText_dev-17.phar/src/cosmicpe/floatingtext/db/D
atabase" at line 19

Error: "Typed property cosmicpe\floatingtext\Loader::$database must not be accessed before initialization" (EXCEPTION) in "plugins/FloatingText_dev-17.phar/src/cosmicpe/floatingtext/Loader" at line 35                    
[04:24:11.319] [Server thread/CRITICAL]: #0 pmsrc/src/plugin/PluginBase(142): cosmicpe\
floatingtext\Loader->onDisable()                                                       
[04:24:11.319] [Server thread/CRITICAL]: #1 pmsrc/src/plugin/PluginManager(422): pocket
mine\plugin\PluginBase->onEnableStateChange(false)                                     
[04:24:11.319] [Server thread/CRITICAL]: #2 pmsrc/src/plugin/PluginManager(411): pocket
mine\plugin\PluginManager->disablePlugin(object cosmicpe\floatingtext\Loader#22446)

**Comment by Muqsit** [comment]
Download the pre-compiled .phar file or install the libasynql virion when running in aa development env.

**Comment by Muqsit** [comment]
Try the new build [FloatingText_dev-18.phar](https://poggit.pmmp.io/r/132563/FloatingText_dev-18.phar) (it ships with a fixed version of libasynql).
